py_library(
    name = "report",
    srcs = [
        "report.py",
    ],
    deps = [
    ],
)

py_test(
    name = "report_test",
    srcs = [
        "test_report.py",
    ],
    deps = [
        "//depot/report:report",
    ],
)
