py_library(
    name = "report",
    srcs = ["report.py"],
    deps = ["//depot/stats:stats"],
)

py_test(
    name = "report_test",
    srcs = ["test_report.py"],
    deps = ["//depot/report:report"],
)
